version: '3'

services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # Dev Environment Variables
      - DEV_APP_ENV=${APP_ENV}
      - DEV_APP_KEY=${APP_KEY}
      - DEV_APP_DEBUG=${APP_DEBUG}
      - DEV_APP_URL=${APP_URL}
      - DEV_DB_CONNECTION=${DB_CONNECTION}
      - DEV_DB_HOST=${DB_HOST}
      - DEV_DB_PORT=${DB_PORT}
      - DEV_DB_DATABASE=${DB_DATABASE}
      - DEV_DB_USERNAME=${DB_USERNAME}
      - DEV_DB_PASSWORD=${DB_PASSWORD}
      - DEV_CACHE_DRIVER=${CACHE_DRIVER}
      - DEV_REDIS_HOST=${REDIS_HOST}
      - DEV_REDIS_PASSWORD=${REDIS_PASSWORD}

      # Staging Environment Variables
      - STAGE_APP_ENV=${APP_ENV_STAGING}
      - STAGE_APP_KEY=${APP_KEY_STAGING}
      - STAGE_APP_DEBUG=${APP_DEBUG_STAGING}
      - STAGE_APP_URL=${APP_URL_STAGING}
      - STAGE_DB_CONNECTION=${DB_CONNECTION_STAGING}
      - STAGE_DB_HOST=${DB_HOST_STAGING}
      - STAGE_DB_PORT=${DB_PORT_STAGING}
      - STAGE_DB_DATABASE=${DB_DATABASE_STAGING}
      - STAGE_DB_USERNAME=${DB_USERNAME_STAGING}
      - STAGE_DB_PASSWORD=${DB_PASSWORD_STAGING}
      - STAGE_CACHE_DRIVER=${CACHE_DRIVER_STAGING}
      - STAGE_REDIS_HOST=${REDIS_HOST_STAGING}
      - STAGE_REDIS_PASSWORD=${REDIS_PASSWORD_STAGING}

      # Production Environment Variables
      - PROD_APP_ENV=${APP_ENV_PRODUCTION}
      - PROD_APP_KEY=${APP_KEY_PRODUCTION}
      - PROD_APP_DEBUG=${APP_DEBUG_PRODUCTION}
      - PROD_APP_URL=${APP_URL_PRODUCTION}
      - PROD_DB_CONNECTION=${DB_CONNECTION_PRODUCTION}
      - PROD_DB_HOST=${DB_HOST_PRODUCTION}
      - PROD_DB_PORT=${DB_PORT_PRODUCTION}
      - PROD_DB_DATABASE=${DB_DATABASE_PRODUCTION}
      - PROD_DB_USERNAME=${DB_USERNAME_PRODUCTION}
      - PROD_DB_PASSWORD=${DB_PASSWORD_PRODUCTION}
      - PROD_CACHE_DRIVER=${CACHE_DRIVER_PRODUCTION}
      - PROD_REDIS_HOST=${REDIS_HOST_PRODUCTION}
      - PROD_REDIS_PASSWORD=${REDIS_PASSWORD_PRODUCTION}

    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www
    links:
      - db
      - redis

  db:
    image: mariadb
    healthcheck:
      test: [ 'CMD','/usr/local/bin/healthcheck.sh','--connect' ]
    environment:
      # Dev Environment Variables
      - DEV_MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DEV_MYSQL_DATABASE=${DB_DATABASE}
      - DEV_MYSQL_USER=${DB_USERNAME}
      - DEV_MYSQL_PASSWORD=${DB_PASSWORD}

      # Staging Environment Variables
      - STAGE_MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD_STAGING}
      - STAGE_MYSQL_DATABASE=${DB_DATABASE_STAGING}
      - STAGE_MYSQL_USER=${DB_USERNAME_STAGING}
      - STAGE_MYSQL_PASSWORD=${DB_PASSWORD_STAGING}

      # Production Environment Variables
      - PROD_MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD_PRODUCTION}
      - PROD_MYSQL_DATABASE=${DB_DATABASE_PRODUCTION}
      - PROD_MYSQL_USER=${DB_USERNAME_PRODUCTION}
      - PROD_MYSQL_PASSWORD=${DB_PASSWORD_PRODUCTION}

    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

volumes:
  db_data:
