FROM php:8.1-apache

COPY --from=composer /usr/bin/composer /usr/bin/composer

# Install required PHP extensions
RUN docker-php-ext-install pdo_mysql

# Install Xdebug
RUN pecl install xdebug-3.1.1 && docker-php-ext-enable xdebug

# Install additional packages
RUN apt-get update && apt-get install -y \
    zip \
    unzip \
    p7zip \
    bash \
    git

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set the working directory
WORKDIR /var/www

# Copy the application code to the container
COPY . .

# Install application dependencies
RUN composer install --prefer-dist --no-dev --optimize-autoloader --no-interaction

# Copy Apache virtual host configuration
COPY docker/apache2.conf /etc/apache2/sites-available/000-default.conf

# Enable Apache modules
RUN a2enmod rewrite headers

# Set environment variables
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
ENV APACHE_LOG_DIR=/var/log/apache2

# Expose the web server port
EXPOSE 80

# Start Apache web server
CMD ["apache2-foreground"]
